### PR TITLE
Fix hash computing command

### PR DESCRIPTION
**Pull request by aleb**
Thanks for the blogpost!

### CODE REVIEW

**Comment by fzakaria** [comment]
So I actually want to compute the NAR Hash; which needs to be uncompressed.
If you remove **xz** it's computing the FileHash.

**Comment by fzakaria** [comment]
(meaning I think the current example is correct)

**Comment by aleb** [comment]
The example is incorrect. Run the command and see what it prints.

**Comment by fzakaria** [comment]
Not seeing it still...they look the same to me.

```
❯ nix path-info /nix/store/p4pclmv1gyja5kzc26npqpia1qqxrf0l-ruby-2.7.3 --store https://cache.nixos.org --json | jq '.[0].narHash'
"sha256:1impfw8zdgisxkghq9a3q7cn7jb9zyzgxdydiamp8z2nlyyl0h5h"
```
```
❯ nix-hash --type sha256 --flat \
       --base32 <(curl --silent https://cache.nixos.org/nar/1w1fff338fvdw53sqgamddn1b2xgds473pv6y13gizdbqjv4i5p3.nar.xz | unxz)
1impfw8zdgisxkghq9a3q7cn7jb9zyzgxdydiamp8z2nlyyl0h5h
```

**Comment by fzakaria** [comment]
Ah whoops wrong section.

**Review by fzakaria — APPROVED** [review]
TY

**Pull request merged**
